XettuyenDGNLTHPT/Controllers/ManageHoSoController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using XettuyenDGNLTHPT.Models;

namespace XettuyenDGNLTHPT.Controllers
{
    public class ManageHoSoController : Controller
    {
        SEP25Team08Entities model = new SEP25Team08Entities();
        // GET: ManageHoSo

        public ActionResult InHoSo()
        {
            var Dot = model.tblDotTuyenSinhDGNLs.ToList();
            List<string> CacDot = new List<string>();
            CacDot.Add("---- Chọn Đợt----");
            foreach (var dot in Dot)
            {
                CacDot.Add("Đợt " + dot.Dot);
            }
            ViewBag.Dot = new SelectList(CacDot);

            return View();
        }
        [HttpPost]
        public ActionResult InHoSo(string Dot, string ddlLoaiXetTuyen, string CMND)
        {
            Session["HoSoDayNe"] = null;
            var form = model.tblFormTuyenSinhs.Find(0);
            var Dot1 = model.tblDotTuyenSinhDGNLs.ToList();
            List<string> CacDot = new List<string>();
            if (form.NgayBatDauEdit <= DateTime.Today && DateTime.Today <= form.NgayKetThucEdit)
            {
                Session["Form-button"] = true;
                if (form.Edit_Open == true)
                {
                    Session["Form-button"] = false;
                }
                else
                {
                    Session["Form-button"] = true;
                }
            }
            else
            {
                Session["Form-button"] = false;
            }
            if (ddlLoaiXetTuyen == "THPT")
            {
                var Hoso = model.tblHoSoTHPTs.FirstOrDefault(u => u.CMND == CMND);
                if (Hoso != null)
                {
                    Session["HoSoDayNe"] = Hoso;

                    CacDot.Add("---- Chọn Đợt----");
                    foreach (var dot in Dot1)
                    {
                        CacDot.Add("Đợt " + dot.Dot);
                    }
                    ViewBag.Dot = new SelectList(CacDot);
                    return View("DetailTHPT", Hoso);
                }
                else
                {
                    var sdt = model.tblHoSoTHPTs.FirstOrDefault(u => u.DienThoaiDD.Equals(CMND.Trim()));
                    if (sdt != null)
                    {
                        Session["HoSoDayNe"] = sdt;

                        CacDot.Add("---- Chọn Đợt----");
                        foreach (var dot in Dot1)
                        {
                            CacDot.Add("Đợt " + dot.Dot);
                        }
                        ViewBag.Dot = new SelectList(CacDot);
                        return View("DetailTHPT", sdt);
                    }
                    Session["notfound"] = true;
                }
            }
            if (ddlLoaiXetTuyen == "DGNL")
            {
                var HosoDGNL = model.tblHoSoDGNLs.FirstOrDefault(u => u.CMND.Equals(CMND.Trim()) && u.Dot.Equals(Dot));
                if (HosoDGNL != null)
                {
                    Session["HoSoDayNe"] = HosoDGNL;

                    CacDot.Add("---- Chọn Đợt----");
                    foreach (var dot in Dot1)
                    {
                        CacDot.Add("Đợt " + dot.Dot);
                    }
                    ViewBag.Dot = new SelectList(CacDot);
                    return View("DetailDGNL", HosoDGNL);
                }
                else
                {
                    var sdt = model.tblHoSoDGNLs.FirstOrDefault(u => u.DienThoaiDD.Equals(CMND.Trim()) && u.Dot.Equals(Dot));
                    if (sdt != null)
                    {
                        Session["HoSoDayNe"] = sdt;

                        CacDot.Add("---- Chọn Đợt----");
                        foreach (var dot in Dot1)
                        {
                            CacDot.Add("Đợt " + dot.Dot);
                        }
                        ViewBag.Dot = new SelectList(CacDot);
                        return View("DetailDGNL", sdt);
                    }
                    Session["notfound"] = true;
                }
            }

            CacDot.Add("---- Chọn Đợt----");
            foreach (var dot in Dot1)
            {
                CacDot.Add("Đợt " + dot.Dot);
            }
            ViewBag.Dot = new SelectList(CacDot);
            return View();
        }


        public ActionResult DetailTHPT(tblHoSoTHPT tHPT)
        {
            var form = model.tblFormTuyenSinhs.Find(0);

            if (form.NgayBatDauEdit <= DateTime.Today && DateTime.Today <= form.NgayKetThucEdit)
            {
                Session["Form-button"] = true;
                if (form.Edit_Open == true)
                {
                    Session["Form-button"] = false;
                }
                else
                {
                    Session["Form-button"] = true;
                }
            }
            else
            {
                Session["Form-button"] = false;
            }
            var Dot = model.tblDotTuyenSinhDGNLs.ToList();
            List<string> CacDot = new List<string>();
            CacDot.Add("---- Chọn Đợt----");
            foreach (var dot in Dot)
            {
                CacDot.Add("Đợt " + dot.Dot);
            }
            ViewBag.Dot = new SelectList(CacDot);
            return View(tHPT);
        }
        [HttpPost]
        public ActionResult DetailTHPT(string Dot, string ddlLoaiXetTuyen, string CMND)
        {
            var form = model.tblFormTuyenSinhs.Find(0);
            var Dot1 = model.tblDotTuyenSinhDGNLs.ToList();
            List<string> CacDot = new List<string>();
            if (form.NgayBatDauEdit <= DateTime.Today && DateTime.Today <= form.NgayKetThucEdit)
            {
                Session["Form-button"] = true;
                if (form.Edit_Open == true)
                {
                    Session["Form-button"] = false;
                }
                else
                {
                    Session["Form-button"] = true;
                }
            }
            else
            {
                Session["Form-button"] = false;
            }
            if (ddlLoaiXetTuyen == "THPT")
            {
                var Hoso = model.tblHoSoTHPTs.FirstOrDefault(u => u.CMND == CMND);
                if (Hoso != null)
                {
                    Session["HoSoDayNe"] = Hoso;

                    CacDot.Add("---- Chọn Đợt----");
                    foreach (var dot in Dot1)
                    {
                        CacDot.Add("Đợt " + dot.Dot);
                    }
                    ViewBag.Dot = new SelectList(CacDot);
                    return View("DetailTHPT", Hoso);
                }
                else
                {
                    var sdt = model.tblHoSoTHPTs.FirstOrDefault(u => u.DienThoaiDD.Equals(CMND.Trim()));
                    if (sdt != null)
                    {
                        Session["HoSoDayNe"] = sdt;

                        CacDot.Add("---- Chọn Đợt----");
                        foreach (var dot in Dot1)
                        {
                            CacDot.Add("Đợt " + dot.Dot);
                        }
                        ViewBag.Dot = new SelectList(CacDot);
                        return View("DetailTHPT", sdt);
                    }
                    Session["notfound"] = true;
                }
            }
            if (ddlLoaiXetTuyen == "DGNL")
            {
                var HosoDGNL = model.tblHoSoDGNLs.FirstOrDefault(u => u.CMND.Equals(CMND.Trim()) && u.Dot.Equals(Dot));
                if (HosoDGNL != null)
                {
                    Session["HoSoDayNe"] = HosoDGNL;

                    CacDot.Add("---- Chọn Đợt----");
                    foreach (var dot in Dot1)
                    {
                        CacDot.Add("Đợt " + dot.Dot);
                    }
                    ViewBag.Dot = new SelectList(CacDot);
                    return View("DetailDGNL", HosoDGNL);
                }
                else
                {
                    var sdt = model.tblHoSoDGNLs.FirstOrDefault(u => u.DienThoaiDD.Equals(CMND.Trim()) && u.Dot.Equals(Dot));
                    if (sdt != null)
                    {
                        Session["HoSoDayNe"] = sdt;

                        CacDot.Add("---- Chọn Đợt----");
                        foreach (var dot in Dot1)
                        {
                            CacDot.Add("Đợt " + dot.Dot);
                        }
                        ViewBag.Dot = new SelectList(CacDot);
                        return View("DetailDGNL", sdt);
                    }
                    Session["notfound"] = true;
                }
            }

            CacDot.Add("---- Chọn Đợt----");
            foreach (var dot in Dot1)
            {
                CacDot.Add("Đợt " + dot.Dot);
            }
            ViewBag.Dot = new SelectList(CacDot);
            tblHoSoTHPT models = Session["HoSoDayNe"] as tblHoSoTHPT;
            if (models != null)
                return View("DetailTHPT", models);

            return View();
        }
        public ActionResult PrintTHPT(tblHoSoTHPT tHPT)
        {
            return View(tHPT);
        }

        public ActionResult DetailDGNL(tblHoSoDGNL dGNL)
        {
            var form = model.tblFormTuyenSinhs.Find(1);

            if (form.NgayBatDauEdit <= DateTime.Today && DateTime.Today <= form.NgayKetThucEdit)
            {
                Session["Form-button"] = true;
                if (form.Edit_Open == true)
                {
                    Session["Form-button"] = false;
                }
                else
                {
                    Session["Form-button"] = true;
                }
            }
            else
            {
                Session["Form-button"] = false;
            }
            var Dot = model.tblDotTuyenSinhDGNLs.ToList();

XettuyenDGNLTHPT/Views/ManageHoSo/InHoSo.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div style="background-color: #c61d23" class="page-header-menu sss">
    <div class="container">
        <div class="hor-menu">
            <ul class="nav navbar-nav">
                <li><a target="_blank" class="amenu" href="http://tuyensinh.vanlanguni.edu.vn/">TUYỂN SINH 2022</a></li>
                @if (Convert.ToBoolean(Session["Form-bodyTHPT"]) == true)
                {

                }
                else
                {
                    <li class="active"><a class="amenu" href="@Url.Action("index", "Home")"> XÉT ĐIỂM THI THPT QG</a></li>
                }
                @if (Convert.ToBoolean(Session["Form-bodyDGNL"]) == true)
                {

                }
                else
                {
                    <li><a class="amenu" href="@Url.Action("index", "HoSoDGNLs")">XÉT ĐIỂM ĐGNL</a></li>
                }


                <li style="background-color: #4e5966"> <a class="amenu" href="@Url.Action("InHoSo", "ManageHoSo")">HỒ SƠ CỦA TÔI</a></li>
                <li><a class="amenu" href="@Url.Action("index", "tracuuketqua")">GIẤY BÁO ĐỦ ĐIỀU KIỆN</a></li>

            </ul>
        </div>
    </div>
</div>
<div id="UpdatePanel1">

    @using (Html.BeginForm("InHoSo", "ManageHoSo", FormMethod.Post))
    {
        <form>

            <div class="aspNetHidden">
                <input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="pc1UmHZMJaISToRTaZ0PDCnlkb0+P0dHHV2FnTCSjsI61w3H3O2oVeD4DqErAGdOYrMfIn8sPU02WwG71lBcpra08zfuOWBIb4pST6pxGWz55FKrDkOwBNA142F6r9KW" />
            </div>

            <div class="aspNetHidden">

                <input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="9D10CFA7" />
                <input type="hidden" name="__EVENTVALIDATION" id="__EVENTVALIDATION" value="ACPVZjx4teabP4d658ST999oEjDO/a6aGtJJC4dkGPvG5OFVSemQywijrq2b56pYqVJYVd0aHufGxdAX5A6sri5+zQhUS+fcDiEzX/YxJI9DLd/PJFA+KbvgjgEg2twwreoIkFkqpiWSojykIistPKZvq35Msxitl7ve4ciMan7Ypu+NV5oZWppH1ba6+VNtqh3/oD/z6NDnLM28Db4gWiT9J/dx/Y3KJ2bV8HEKQ8A=" />
            </div>
            <div class="page-container">
                <!-- BEGIN CONTENT -->

            @if (Convert.ToBoolean(Session["notfound"]) == true)
            {
                Session["notfound"] = false;
                <div style="font-size:1.3em" class="text-center font-blue bold">
                    <br>Không tìm thấy hồ sơ của bạn trên hệ thống!<br>Bạn cần nhập đúng SỐ CMND/CCCD hoặc SỐ ĐIỆN THOẠI đã đăng ký hồ sơ.<br><br>Nếu cần hỗ trợ, bạn có thể liên hệ hotline: (028) 7105 9999
                </div>
            }
            <div class="page-content-wrapper">
                <!-- BEGIN CONTENT BODY -->
                <!-- BEGIN PAGE CONTENT BODY -->
                <div class="page-content" style="background-color: white">
                    <p></p>
                    <div class="row">
                        <div class="col-md-1"></div>
                        <div class="col-md-2" id="dot">
                            @Html.DropDownList("Dot", (IEnumerable<SelectListItem>)ViewBag.Dot, null, new { @class = "form-control", @style = " width: 255px;    height: 40px; " })
                        </div>
                        <div class="col-md-2">
                            <select name="ddlLoaiXetTuyen" id="ddlLoaiXetTuyen" class="form-control">
                                <option value="THPT">THPT QG</option>
                                <option value="DGNL">Đ&#225;nh gi&#225; năng lực</option>

                                </select>
                            </div>

                            <div class="col-md-4"><input name="CMND" id="CMND" placeholder="NHẬP CMND/CCCD HOẶC SỐ ĐIỆN THOẠI" type="text" class="form-control" /></div>
                            <div class="col-md-2"><input type="submit" name="btnTim" value="TÌM HỒ SƠ" class="btn green button-submit" /></div>

                            <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br>
                            <div class="col-md-2"></div>
                        </div>


                    </div>

                    <div class="vertical_space"></div>
                    <div class="vertical_space"></div>
                    <div class="vertical_space"></div>
                    <div class="vertical_space"></div>
                    <div class="vertical_space"></div>
                </div>

            </div>
        </form>


    }
</div>
@section Scripts {
    <script src="~/Scripts/app.js"></script>

    @Scripts.Render("~/bundles/jqueryval")
    <script>
        let data = $("#ddlLoaiXetTuyen :selected").val();
        if (data == 'THPT') {
            $('#Dot').hide();
        }
        $('#ddlLoaiXetTuyen').change(function () {
            $('#ddlLoaiXetTuyen option').each(function () {
                if ($(this).val() == "DGNL") {
                    $('#Dot').toggle();
                }
            });

        });
    </script>
}

XettuyenDGNLTHPT/Views/ManageHoSo/SaveDGNL.cshtml
@{
    ViewBag.Title = "Save";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div style="background-color: #c61d23" class="page-header-menu sss">
    <div class="container">
        <div class="hor-menu">
            <ul class="nav navbar-nav">
                <li><a target="_blank" class="amenu" href="http://tuyensinh.vanlanguni.edu.vn/">TUYỂN SINH 2022</a></li>
                @if (Convert.ToBoolean(Session["Form-bodyTHPT"]) == true)
                {

                }
                else
                {
                    <li><a class="amenu" href="@Url.Action("index", "Home")"> XÉT ĐIỂM THI THPT QG</a></li>
                }
                @if (Convert.ToBoolean(Session["Form-bodyDGNL"]) == true)
                {

                }
                else
                {
                    <li><a class="amenu" href="@Url.Action("index", "HoSoDGNLs")">XÉT ĐIỂM ĐGNL</a></li>
                }


                <li style="background-color: #4e5966"> <a class="amenu" href="@Url.Action("InHoSo", "ManageHoSo")">HỒ SƠ CỦA TÔI</a></li>
                <li><a class="amenu" href="@Url.Action("index", "tracuuketqua")">GIẤY BÁO ĐỦ ĐIỀU KIỆN</a></li>

            </ul>
        </div>
    </div>
</div>
<DIV class="page-container">
    <!-- BEGIN CONTENT -->
    <br><H3><div class='text-center font-red bold'>Chúc mừng! Bạn đã đăng ký xét tuyển thành công.</div></H3><div class='text-center'><h4>Mã hồ sơ của bạn là: <b>DVL_@Model.ID</b><p><br>Nhà Trường đã gửi thông báo đến email (bạn đã đăng ký). Hãy kiểm tra email để nắm thông tin và làm theo hướng dẫn nhé.</h4></div><p>
        <br><H3><div class='text-center font-blue bold'>Chúc bạn đạt kết quả như ý và gia nhập thế hệ sinh viên của Văn Lang!</div></H3>
            <DIV class="page-content-wrapper">
                <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
                <!-- BEGIN CONTENT BODY -->
                <!-- BEGIN PAGE CONTENT BODY -->
                <DIV class="page-content">
                    <DIV class="container">
                        <!-- BEGIN PAGE CONTENT INNER -->
                        <DIV class="page-content-inner">

                        </DIV>
                    </DIV>
                </DIV>
            </DIV>
</DIV>

XettuyenDGNLTHPT/Views/ManageHoSo/SaveTHPT.cshtml
@{
    ViewBag.Title = "Save";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <div style="background-color: #c61d23" class="page-header-menu sss">
        <div class="container">
            <div class="hor-menu">
                <ul class="nav navbar-nav">
                    <li><a target="_blank" class="amenu" href="http://tuyensinh.vanlanguni.edu.vn/">TUYỂN SINH 2022</a></li>
                    @if (Convert.ToBoolean(Session["Form-bodyTHPT"]) == true)
                    {

                    }
                    else
                    {
                        <li><a class="amenu" href="@Url.Action("index", "Home")"> XÉT ĐIỂM THI THPT QG</a></li>
                    }
                    @if (Convert.ToBoolean(Session["Form-bodyDGNL"]) == true)
                    {

                    }
                    else
                    {
                        <li><a class="amenu" href="@Url.Action("index", "HoSoDGNLs")">XÉT ĐIỂM ĐGNL</a></li>
                    }


                    <li style="background-color: #4e5966"> <a class="amenu" href="@Url.Action("InHoSo", "ManageHoSo")">HỒ SƠ CỦA TÔI</a></li>
                    <li><a class="amenu" href="@Url.Action("index", "tracuuketqua")">GIẤY BÁO ĐỦ ĐIỀU KIỆN</a></li>

                </ul>
            </div>
        </div>
    </div>
    <DIV class="page-container">
        <!-- BEGIN CONTENT -->
        <br><H3><div class='text-center font-red bold'>Chúc mừng! Bạn đã đăng ký xét tuyển thành công.</div></H3><div class='text-center'><h4>Mã hồ sơ của bạn là: <b>DVL_@Model.ID</b><p><br>Nhà Trường đã gửi thông báo đến email (bạn đã đăng ký). Hãy kiểm tra email để nắm thông tin và làm theo hướng dẫn nhé.</h4></div><p>
            <br><H3><div class='text-center font-blue bold'>Chúc bạn đạt kết quả như ý và gia nhập thế hệ sinh viên của Văn Lang!</div></H3>
            <DIV class="page-content-wrapper">
                <!-- BEGIN CONTENT BODY -->
                <!-- BEGIN PAGE CONTENT BODY -->
                <DIV class="page-content">
                    <DIV class="container">
                        <!-- BEGIN PAGE CONTENT INNER -->
                        <DIV class="page-content-inner">

                        </DIV>
                    </DIV>
                </DIV>
            </DIV>
    </DIV>