XettuyenDGNLTHPT/Areas/Admin/Controllers/AcountController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Windows.Forms;
using XettuyenDGNLTHPT.Areas.Admin.Middleware;
using XettuyenDGNLTHPT.Models;

namespace XettuyenDGNLTHPT.Areas.Admin.Controllers
{
    public class AcountController : Controller
    {
        SEP25Team08Entities model = new SEP25Team08Entities();
        // GET: Admin/Login_Logout
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(string username,string password)
        {
            var user = model.Accounts.FirstOrDefault(u => u.Username.Equals(username));
            if(user != null)
            {
                if (user.Password.Equals(password))
                {
                    Session["usser-fullname"] = user.Full_Name;
                    Session["user-id"] = user.ID;
                    Session["user-role"] = user.Role;
                    return RedirectToAction("Index","HomeAdmin");
                }
                else
                {
                    Session["password-incorrect"] = true;
                    return View();
                }
            }
            Session["username-incorrect"] = true;
            return View();
        }
        public ActionResult Logout(string confirm_value)
        {
            
          Session["usser-fullname"] = null;
         Session["user-id"] = null;
         Session["user-role"] = null;
         return View("Login");
  
        }
        [LoginVerification]
        public ActionResult AddAccount()
        {

            return View();
        }
        [HttpPost]
        public ActionResult AddAccount(Account account, string repass, string role)
        {
            var thongtin = account;
            if (account.Password.Equals(repass))
            {
                if (role.Equals("1"))
                {
                    thongtin.Role = "1";
                    model.Accounts.Add(thongtin);
                    model.SaveChanges();
                    return RedirectToAction("Index","HomeAdmin");
                }
                else
                {
                    thongtin.Role = "0";
                    model.Accounts.Add(thongtin);
                    model.SaveChanges();
                    return RedirectToAction("Index", "HomeAdmin");
                }
            }
            else
            {
                
            }
            
            return View();
        }
        [LoginVerification]
        public ActionResult EditAccount(int id)
        {
            var thongtin = model.Accounts.Find(id);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(thongtin);
        }
        [HttpPost]
        public ActionResult EditAccount(Account account, string repass, string role)
        {
            if (ModelState.IsValid)
            {
                var thongtin = account;
                if (account.Password.Equals(repass))
                {
                    if (role.Equals("1"))
                    {
                        
                        thongtin.Role = "1";
                        model.Entry(thongtin).State = EntityState.Modified;
                        model.SaveChanges();
                        return RedirectToAction("Index", "HomeAdmin");
                    }
                    else
                    {
                        SEP25Team08Entities db = new SEP25Team08Entities();
                        var roletk = db.Accounts.ToList();
                        int count = roletk.Count(u => u.Role == "1");
                        if(count <= 1)
                        {
                            ViewBag.ErrorMessage = "Cần có 1 quản trị";
                            return View();
                        }
                        else
                        {
                            thongtin.Role = "0";
                            model.Entry(thongtin).State = EntityState.Modified;
                            model.SaveChanges();
                            return RedirectToAction("Index", "HomeAdmin");
                        }

                    }
                }
                else
                {
                    ModelState.AddModelError("", "Mật khẩu không trùng khớp");
                }
            }
            return View();
        }
        [LoginVerification]
        public ActionResult DeleteAccount(int id)
        {
            var xoa = model.Accounts.Find(id);
            model.Accounts.Remove(xoa);
            model.SaveChanges();
            return RedirectToAction("ManageAcount","HomeAdmin");
        }


    }
}

XettuyenDGNLTHPT/Areas/Admin/Views/Acount/AddAccount.cshtml
@model XettuyenDGNLTHPT.Models.Account

@{
    ViewBag.Title = "AddAccount";
    Layout = "~/Areas/Admin/Views/Shared/_adminlayout.cshtml";
}



@using (Html.BeginForm("AddAccount","Acount"))
{
    @Html.AntiForgeryToken()
   
        <div class="container-fluid" style="padding: 30px">

            <div class="row">
                <div class="col-md-12 col-lg-12 col-sm-12">
                    <div class="white-box">
                        <h3>Thêm Tài khoản</h3>
                        <form class="bg-light p-4 m-4">
                            <div class="form-group">
                                <label for="yourmail">Họ và Tên:</label>
                                @Html.EditorFor(model => model.Full_Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập họ và tên", required = "true" } })
                                @Html.ValidationMessageFor(model => model.Full_Name, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                <label for="yourmail">Email:</label>
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập email" , required = "true" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="yourmail">Số điện thoại</label>
                                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập số điện thoại", required = "true" } })
                                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="yourmail">Tên Đăng Nhập</label>
                                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" ,placeholder = "Nhập tên đăng nhâp", required = "true" } })
                                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })    
                            </div>
                            <div class="form-group">
                                <label for="yourmail">Mật Khẩu</label>
                                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập mật khẩu", type = "password", required = "true" } })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="yourmail">Nhập lại mật khẩu</label>
                                <input type="password" class="form-control" name="repass" placeholder="Nhập lại mật khẩu" , required = "true">
                            </div>
                            <div class="form-group">
                                <label for="yourmail">Chọn quyền:</label>
                                <select  name="role" style=" width: 155px;
                                        height: 35px; text-align: center; font-size: 15px;", required = "true">
                                    <option value="">-----Chọn Quyền-----</option>
                                    <option value="1">Quản Trị</option>
                                    <option value="0">Quản Lý</option>
                                </select>
                            </div>
                            <button class="btn-messger btn btn-success btn-save" onclick="document.getElementById('id01').style.display='block'">Đăng Ký</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
     
   
}

XettuyenDGNLTHPT/Areas/Admin/Views/Acount/EditAccount.cshtml
@model XettuyenDGNLTHPT.Models.Account

@{
    ViewBag.Title = "EditAccount";
    Layout = "~/Areas/Admin/Views/Shared/_adminlayout.cshtml";
}



@using (Html.BeginForm())
{
   
    @Html.AntiForgeryToken()


        <div class="container-fluid" style="padding: 30px">

            <div class="row">
                <div class="col-md-12 col-lg-12 col-sm-12">
                    <div class="white-box">
                        <h3>Chỉnh sửa tài khoản</h3>
                        <form class="bg-light p-4 m-4">
                            <div class="form-group">
                                <label for="yourmail">Họ và Tên:</label>
                                @Html.EditorFor(model => model.Full_Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập họ và tên", required = "true" } })
                                @Html.ValidationMessageFor(model => model.Full_Name, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                <label for="yourmail">Email:</label>
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập email", required = "true" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="yourmail">Số điện thoại</label>
                                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập số điện thoại", required = "true" } })
                                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="yourmail">Tên Đăng Nhập</label>
                                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập tên đăng nhâp", required = "true" } })
                                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="yourmail">Mật Khẩu</label>
                                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", placeholder = "Nhập mật khẩu", type = "password", required = "true" } })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="yourmail">Nhập lại mật khẩu</label>
                                <input type="password" class="form-control" name="repass" placeholder="Nhập lại mật khẩu" , required="true">
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label for="yourmail">Chọn quyền:</label>
                                <select name="role" style=" width: 155px;
                                        height: 35px; text-align: center; font-size: 15px;" , required="true">
                                    <option value="">-----Chọn Quyền-----</option>
                                    <option value="1">Quản Trị</option>
                                    <option value="0">Quản Lý</option>
                                </select>
                                <p  class = "text-danger">@ViewBag.ErrorMessage</p>
                            </div>
                            <button class="btn-messger btn btn-success btn-save"  onclick="if (!confirm ('Bạn có muốn lưu thông tin tài khoản không?')) { return false; }">Đăng Ký</button>

                        </form>
                    </div>
                </div>
            </div>
       

    </div>
}

XettuyenDGNLTHPT/Areas/Admin/Views/Acount/Login.cshtml
@{
    Layout = null;
}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
<head>
    <title>Login Page</title>
    <!--Made with love by Mutiullah Samim -->
    <!--Bootsrap 4 CDN-->
    <link rel="icon" type="image/png" sizes="16x16" href="~/assets/adminsep/plugins/images/logo-page.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!--Fontawesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <!--Custom styles-->
    <link href="~/assets/adminsep/css/style.login.css" rel="stylesheet" />
</head>
<body>
    <b class="logo-icon">
        <!-- Dark Logo icon -->
        <img style="margin: 10px;" src="https://elearning.vanlanguni.edu.vn/pluginfile.php/1/theme_klass/logo/1639091210/logo-vlu-en-8.png" alt="homepage" />
    </b>
    <div class="container">
        <div class="d-flex justify-content-center h-60">
            <div class="card">
                <div class="card-header">
                    <h3>Sign In</h3>
                    <div class="d-flex justify-content-end social_icon">

                        <span><b><i style="font-size:" class="fab  fa-solid fa-user-vneck-hair">VLU</i></b></span>

                    </div>
                </div>
                <div class="card-body">
                    <form action="@Url.Action("Login")" method="post">

                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input type="text" class="form-control" placeholder="username" name="username">

                        </div>

                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            <input type="password" class="form-control" placeholder="password" name="password">
                        </div>
                        @if (Convert.ToBoolean(Session["password-incorrect"]) == true || Convert.ToBoolean(Session["username-incorrect"]) == true)
                        {
                            <p style="color:red">Tài khoản hoặc mật khẩu sai, vui lòng đăng nhập lại </p>
                        }
                        <div class="form-group">
                            <input type="submit" value="Login" class="btn float-right login_btn">
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-center links">
                        Đạo Đức - Ý Chí - Sáng Tạo
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</body>
</html>