XettuyenDGNLTHPT/Areas/Admin/Controllers/ManageTHPTController.cs
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XettuyenDGNLTHPT.Areas.Admin.Middleware;
using XettuyenDGNLTHPT.Models;

namespace XettuyenDGNLTHPT.Areas.Admin.Controllers
{
    [LoginVerification]
    public class ManageTHPTController : Controller
    {

        // GET: Admin/ManageTHPT
        SEP25Team08Entities model = new SEP25Team08Entities();
        public ActionResult Index()
        {
            var list = model.tblHoSoTHPTs.ToList();
            return View(list);
        }

        // GET: Admin/ManageTHPT/Details/5
        public ActionResult DetailsHoSoTHPT(int id)
        {
            var dthsTHPT = model.tblHoSoTHPTs.Find(id);
            if(dthsTHPT.MaNganh_ToHop1 !=null && dthsTHPT.MaNganh_ToHop2 !=null && dthsTHPT.MaNganh_ToHop3 != null)
            {
                Session["SonguyenVOng"] = 3;
            }else if(dthsTHPT.MaNganh_ToHop1 != null && dthsTHPT.MaNganh_ToHop2 != null)
            {
                Session["SonguyenVOng"] = 2;
            }
            else
            {
                Session["SonguyenVOng"] = 1;
            }
            return View(dthsTHPT);
        }

        public JsonResult NhanHoSo(string id, string vlue)
        {
            int sid = Int32.Parse(id.Trim());
            var nhanhosoTHPT = model.tblHoSoTHPTs.Where(h => h.ID == sid).FirstOrDefault();
            if (string.IsNullOrEmpty(vlue))
            {
                nhanhosoTHPT.DaNhanHoSo = null;
                model.Entry(nhanhosoTHPT).State = EntityState.Modified;
                model.SaveChanges();
            }
            else
            {
                nhanhosoTHPT.DaNhanHoSo = "N";
                model.Entry(nhanhosoTHPT).State = EntityState.Modified;
                model.SaveChanges();
            }
            return Json("Success");
        }
        public ActionResult ExportData()
        {
            var list = model.tblHoSoTHPTs.ToList();
            ExcelPackage ep = new ExcelPackage();
            ExcelWorksheet Sheet = ep.Workbook.Worksheets.Add("Report");
            Sheet.Cells["A1"].Value = "Mã hồ sơ";
            Sheet.Cells["B1"].Value = "Họ và tên";
            Sheet.Cells["C1"].Value = "Email";
            Sheet.Cells["D1"].Value = "Giới tính";
            Sheet.Cells["E1"].Value = "Ngày sinh";
            Sheet.Cells["F1"].Value = "Mã nơi sinh";
            Sheet.Cells["G1"].Value = "Tên nơi sinh";
            Sheet.Cells["H1"].Value = "Mã dân tôc";
            Sheet.Cells["I1"].Value = "Tên dân tộc";
            Sheet.Cells["J1"].Value = "Mã tôn giáo";
            Sheet.Cells["K1"].Value = "Tên tôn giáo";
            Sheet.Cells["L1"].Value = "CMND";
            Sheet.Cells["M1"].Value = "Quốc tịch";
            Sheet.Cells["N1"].Value = "Hộ Khẩu";
            Sheet.Cells["O1"].Value = "Hộ khẩu Mã phường";
            Sheet.Cells["P1"].Value = "Hộ khẩu Tên phường";
            Sheet.Cells["Q1"].Value = "Hộ khẩu Mã tỉnh TP";
            Sheet.Cells["R1"].Value = "Hộ khẩu Tên tỉnh TP";
            Sheet.Cells["S1"].Value = "Hộ khẩu Mã quận huyện";
            Sheet.Cells["T1"].Value = "Hộ khẩu Tên quận huyện";
            Sheet.Cells["U1"].Value = "Năm tốt nghiệp";
            Sheet.Cells["V1"].Value = "Số báo danh";
            Sheet.Cells["W1"].Value = "Hạnh kiểm lớp 12";
            Sheet.Cells["X1"].Value = "Học lực lớp 12";
            Sheet.Cells["Y1"].Value = "Loại hình TN";
            Sheet.Cells["Z1"].Value = "Trường THPT Mã Tỉnh";
            Sheet.Cells["AA1"].Value = "Trường THPT Tên Tỉnh";
            Sheet.Cells["AB1"].Value = "Trường THPT Mã Quận/Huyện";
            Sheet.Cells["AC1"].Value = "Trường THPT Tên Quận/Huyện";
            Sheet.Cells["AD1"].Value = "Tên Trường THPT";
            Sheet.Cells["AE1"].Value = "Mã Trường THPT";
            Sheet.Cells["AF1"].Value = "Tên lớp 12";
            Sheet.Cells["AG1"].Value = "Khu vực";
            Sheet.Cells["AH1"].Value = "Đối tượng ưu tiên";
            Sheet.Cells["AI1"].Value = "Toán";
            Sheet.Cells["AJ1"].Value = "Văn";
            Sheet.Cells["AK1"].Value = "Anh";
            Sheet.Cells["AL1"].Value = "Pháp";
            Sheet.Cells["AM1"].Value = "Lý";
            Sheet.Cells["AN1"].Value = "Hóa";
            Sheet.Cells["AO1"].Value = "Sinh";
            Sheet.Cells["AP1"].Value = "Sử";
            Sheet.Cells["AQ1"].Value = "Địa ";
            Sheet.Cells["AR1"].Value = "GDCD";
            Sheet.Cells["AS1"].Value = "CCNN";
            Sheet.Cells["AT1"].Value = "Mã ngành_tổ hợp 1";
            Sheet.Cells["AU1"].Value = "Tên ngành_tổ hợp 1";
            Sheet.Cells["AV1"].Value = "CTDT 1";
            Sheet.Cells["AW1"].Value = "Mã ngành_tổ hợp 2";
            Sheet.Cells["AX1"].Value = "Tên ngành_tổ hợp 2";
            Sheet.Cells["AY1"].Value = "CTDT 2";
            Sheet.Cells["AZ1"].Value = "Mã ngành_tổ hợp 3";
            Sheet.Cells["BA1"].Value = "Tên ngành_tổ hợp 3";
            Sheet.Cells["BB1"].Value = "CTDT 3";
            Sheet.Cells["BC1"].Value = "Liên lạc địa chỉ";
            Sheet.Cells["BD1"].Value = "Liên lạc mã phường";
            Sheet.Cells["BE1"].Value = "Liên lạc tên phường";
            Sheet.Cells["BF1"].Value = "Liên lạc mã tỉnh tp";
            Sheet.Cells["BG1"].Value = "Liên lạc tên tỉnh tp";
            Sheet.Cells["BH1"].Value = "liên lạc mã quận/huyện";
            Sheet.Cells["BI1"].Value = "Liên lạc tên quận/huyện";
            Sheet.Cells["BJ1"].Value = "Điện thoại di động";
            Sheet.Cells["BK1"].Value = "Điện thoại phụ huynh";
            Sheet.Cells["BL1"].Value = "Data Inserted";
            Sheet.Cells["BM1"].Value = "Data Edited";
            Sheet.Cells["BN1"].Value = "Đã Nhận Hồ sơ";
            Sheet.Cells["BO1"].Value = "Điểm vẽ mỹ thuật";
            Sheet.Cells["BP1"].Value = "Điểm vẽ năng khiếu";
            int row = 2;// dòng bắt đầu ghi dữ liệu
            foreach (var item in list)
            {
                Sheet.Cells[string.Format("A{0}", row)].Value = item.ID;
                Sheet.Cells[string.Format("B{0}", row)].Value = item.HoVaTen;
                Sheet.Cells[string.Format("C{0}", row)].Value = item.Email;
                if (item.GioiTinh == true)
                {
                    Sheet.Cells[string.Format("D{0}", row)].Value = "Nam";
                }
                else if (item.GioiTinh == false)
                {
                    Sheet.Cells[string.Format("D{0}", row)].Value = "Nữ";
                }
                else
                {
                    Sheet.Cells[string.Format("D{0}", row)].Value = "";
                }
                Sheet.Cells[string.Format("E{0}", row)].Value = Convert.ToDateTime(item.NgaySinh).ToString("dd/MM/yyyy");
                Sheet.Cells[string.Format("F{0}", row)].Value = item.MaNoiSinh;
                Sheet.Cells[string.Format("G{0}", row)].Value = item.TenNoiSinh;
                Sheet.Cells[string.Format("H{0}", row)].Value = item.MaDanToc;
                Sheet.Cells[string.Format("I{0}", row)].Value = item.TenDanToc;
                Sheet.Cells[string.Format("J{0}", row)].Value = item.MaTonGiao;
                Sheet.Cells[string.Format("K{0}", row)].Value = item.TenTonGiao;
                Sheet.Cells[string.Format("L{0}", row)].Value = item.CMND;
                Sheet.Cells[string.Format("M{0}", row)].Value = item.QuocTich;
                Sheet.Cells[string.Format("N{0}", row)].Value = item.HoKhau;
                Sheet.Cells[string.Format("O{0}", row)].Value = item.HoKhau_MaPhuong;
                Sheet.Cells[string.Format("P{0}", row)].Value = item.HoKhau_TenPhuong;
                Sheet.Cells[string.Format("Q{0}", row)].Value = item.HoKhau_MaTinhTP;
                Sheet.Cells[string.Format("R{0}", row)].Value = item.HoKhau_TenTinhTP;
                Sheet.Cells[string.Format("S{0}", row)].Value = item.HoKhau_MaQH;
                Sheet.Cells[string.Format("T{0}", row)].Value = item.HoKhau_TenQH;
                Sheet.Cells[string.Format("U{0}", row)].Value = item.NamTotNghiep;
                Sheet.Cells[string.Format("V{0}", row)].Value = item.SoBaoDanh;
                Sheet.Cells[string.Format("W{0}", row)].Value = item.HocLucLop12;
                Sheet.Cells[string.Format("X{0}", row)].Value = item.HanhKiemLop12;
                Sheet.Cells[string.Format("Y{0}", row)].Value = item.LoaiHinhTN;
                Sheet.Cells[string.Format("Z{0}", row)].Value = item.TruongTHPT_MaTinhTP;
                Sheet.Cells[string.Format("AA{0}", row)].Value = item.TruongTHPT_TenTinhTP;
                Sheet.Cells[string.Format("AB{0}", row)].Value = item.TruongTHPT_MaQH;
                Sheet.Cells[string.Format("AC{0}", row)].Value = item.TruongTHPT_TenQH;
                Sheet.Cells[string.Format("AD{0}", row)].Value = item.TenTruongTHPT;
                Sheet.Cells[string.Format("AE{0}", row)].Value = item.MaTruongTHPT;
                Sheet.Cells[string.Format("AF{0}", row)].Value = item.TenLop12;
                Sheet.Cells[string.Format("AG{0}", row)].Value = item.KhuVuc;
                Sheet.Cells[string.Format("AH{0}", row)].Value = item.DoiTuongUuTien;
                Sheet.Cells[string.Format("AI{0}", row)].Value = item.Toan;
                Sheet.Cells[string.Format("AJ{0}", row)].Value = item.Van;
                Sheet.Cells[string.Format("AK{0}", row)].Value = item.Anh;
                Sheet.Cells[string.Format("AL{0}", row)].Value = item.Phap;
                Sheet.Cells[string.Format("AM{0}", row)].Value = item.Ly;
                Sheet.Cells[string.Format("AN{0}", row)].Value = item.Hoa;
                Sheet.Cells[string.Format("AO{0}", row)].Value = item.Sinh;
                Sheet.Cells[string.Format("AP{0}", row)].Value = item.Su;
                Sheet.Cells[string.Format("AQ{0}", row)].Value = item.Dia;
                Sheet.Cells[string.Format("AR{0}", row)].Value = item.GDCD;

XettuyenDGNLTHPT/Areas/Admin/Views/ManageTHPT/DetailsHoSoTHPT.cshtml
@model XettuyenDGNLTHPT.Models.tblHoSoTHPT

@{
    ViewBag.Title = "DetailsHoSoTHPT";
    Layout = "~/Areas/Admin/Views/Shared/_adminlayout.cshtml";
}

<!DOCTYPE html>
<html dir="ltr" lang="en">



<body>
    <script>
        var mybutton = document.getElementById("myBtn");
        window.onscroll = function () { scrollFunction() };

        function scrollFunction() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                mybutton.style.display = "block";
            } else {
                mybutton.style.display = "none";
            }
        }
        function topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;

        }
    </script>
    <div class="page-breadcrumb bg-white">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title" style="line-height: 40px; padding-top: 10px">Hồ Sơ Xét Tuyển THPT Quốc Gia</h4>
            </div>

        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="container-fluid">

        <div class="row">
            <div class="row">
                <div class="col-md-12 col-lg-12 col-sm-12">
                    <div class="col-md-3 col-sm-4 col-xs-6 ms-auto">

                    </div>
                    <div class="white-box">
                        <div style="display: flex; justify-content: space-between;" class="d-md-flex mb-3">
                            <h3 style="color: red" class="">THÔNG TIN THÍ SINH: </h3>



                        </div>
                        <div class="table-responsive">
                            <table class="table no-wrap">
                                <thead>
                                    <tr>
                                        <th colspan="4" class="border-top-0">Mã Hồ Sơ: <b>DVL_@Model.ID</b></th>
                                        <th colspan="4" class="border-top-0">Trạng thái : <b>@Model.DaNhanHoSo</b></th>

                                    </tr>
                                </thead>
                                <tbody>
                                    <!--     -->
                                    <tr>
                                        <td style=" line-height: 35px;">Họ và tên: <b>@Model.HoVaTen</b></td>
                                        <td style=" line-height: 35px;" class="txt-oflo">Ngày sinh: <b>@Convert.ToDateTime(@Model.NgaySinh).ToString("dd/MM/yyyy")</b></td>
                                        @if (Model.GioiTinh == true)
                                        {
                                            <td style=" line-height: 35px;">Giới tính: <b>Nam</b></td>
                                        }
                                        else
                                        {
                                            <td style=" line-height: 35px;">Giới tính: <b>Nữ</b></td>
                                        }

                                        <td style=" line-height: 35px;" class="txt-oflo">CCCD/CMND: <b>@Model.CMND</b></td>
                                    </tr>
                                    <tr>
                                        <td style=" line-height: 35px;">Trường THPT - Lớp: <b>@Model.TenTruongTHPT - @Model.TenLop12</b></td>
                                        <td style=" line-height: 35px;" class="txt-oflo">Trường THPT Thuộc Tỉnh/TP: <b>@Model.TruongTHPT_TenTinhTP</b></td>
                                        <td style=" line-height: 35px;">Năm tốt nghiệp THPT: <b>@Model.NamTotNghiep</b></td>
                                        <td style=" line-height: 35px;" class="txt-oflo">Loại hình tốt nghiệp: <b>@Model.LoaiHinhTN</b></td>
                                    </tr>
                                    <tr>
                                        <td style=" line-height: 35px;">Số điện thoại: <b>@Model.DienThoaiDD</b></td>
                                        <td style=" line-height: 35px;" class="txt-oflo">Email: <b>@Model.Email</b></td>
                                        <td style=" line-height: 35px;">Khu vực: <b>@Model.KhuVuc</b></td>
                                        <td style=" line-height: 35px;" class="txt-oflo">Đối tượng ưu tiên: <b>@Model.DoiTuongUuTien</b></td>
                                    </tr>
                                    <tr>
                                        <th colspan="4" style=" line-height: 35px;">Hộ khẩu: <b>@Model.HoKhau, @Model.HoKhau_TenPhuong, @Model.HoKhau_TenQH, @Model.HoKhau_TenTinhTP</b></th>
                                    </tr>
                                    <tr>
                                        <th colspan="4" style=" line-height: 35px;">Địa chỉ liên hệ: <b>@Model.LienLac_DiaChi, @Model.LienLac_TenPhuongXa, @Model.LienLac_TenQH, @Model.LienLac_TenTP</b></th>
                                    </tr>
                                    <tr>
                                        <th colspan="4" style=" line-height: 35px;">Quốc tịch: <b>@Model.QuocTich</b></th>
                                    </tr>

                                    <!--     -->
                                    <!--     -->
                                    <!--     -->
                                </tbody>

                            </table>
                            <center> <hr style="height: 3px; width: 90%; "></center>
                            <table class="table no-wrap">
                                <thead>
                                    <tr>
                                        <th colspan="4" class="border-top-0"><h3>THÔNG TIN XÉT TUYỂN</h3></th>


                                    </tr>
                                </thead>
                                <tbody>
                                    <!--     -->
                                    <tr>
                                        <td style=" line-height: 35px;">Phương thức xét tuyển: <b>THPT QG</b></td>

                                        <td colspan="" style=" line-height: 35px;">Số nguyện vọng: <b>@Session["SonguyenVOng"]</b></td>

                                    </tr>

                                    <tr>
                                        <td colspan="" style=" line-height: 35px;" class="txt-oflo">Toán: <b>@Model.Toan</b></td>
                                        <td colspan="" style=" line-height: 35px;" class="txt-oflo">Anh: <b>@Model.Anh</b></td>
                                        <td colspan="" style=" line-height: 35px;" class="txt-oflo">Văn: <b>@Model.Van</b></td>
                                        <td colspan="" style=" line-height: 35px;" class="txt-oflo">Lý: <b>@Model.Ly</b></td>
                                        <td colspan="" style=" line-height: 35px;" class="txt-oflo">Sinh: <b>@Model.Sinh</b></td>
                                        <td colspan="" style=" line-height: 35px;" class="txt-oflo">Sử: <b>@Model.Su</b></td>
                                        <td colspan="" style=" line-height: 35px;" class="txt-oflo">Địa: <b>@Model.Dia</b></td>
                                        <td colspan="" style=" line-height: 35px;" class="txt-oflo">GDCD: <b>@Model.GDCD</b></td>
                                        <td colspan="" style=" line-height: 35px;" class="txt-oflo">Phap: <b>@Model.Phap</b></td>
                                    </tr>

                                    <tr>
                                        <th colspan="4" style=" line-height: 35px;">Chứng chỉ ngoại ngữ: <b>@Model.CCNN</b></th>
                                    </tr>
                                    <tr>
                                        <th colspan="" class="">Nguyện Vọng</th>
                                        <th colspan="" class="border-top-0">Ngành</th>
                                        <th colspan="" class="border-top-0">Mã Ngành</th>
                                        <th>Chương trình học</th>


                                    </tr>
                                    <tr>
                                        <td style=" line-height: 35px;">1</td>
                                        <td style=" line-height: 35px;" class="txt-oflo">@Model.TenNganh_TenToHop1.Split('#')[0]</td>
                                        <td style=" line-height: 35px;">@Model.MaNganh_ToHop1.Split('#')[0]</td>
                                        <td style=" line-height: 35px;" class="txt-oflo">@Model.CTDT1</td>
                                    </tr>
                                    <tr>
                                        <td style=" line-height: 35px;">2</td>
                                        @if (@Model.TenNganh_TenToHop2 == null)
                                        {
                                            <td style=" line-height: 35px;"> @Model.TenNganh_TenToHop2</td>
                                        }
                                        else
                                        {
                                            <td style=" line-height: 35px;">@Model.TenNganh_TenToHop2.Split('#')[0]</td>
                                        }
                                        @if (@Model.MaNganh_ToHop2 == null)
                                        {
                                            <td style=" line-height: 35px;"> @Model.MaNganh_ToHop2</td>
                                        }
                                        else
                                        {
                                            <td style=" line-height: 35px;">@Model.MaNganh_ToHop2.Split('#')[0]</td>
                                        }

                                        <td style=" line-height: 35px;" class="txt-oflo">@Model.CTDT2</td>
                                    </tr>
                                    <tr>
                                        <td style=" line-height: 35px;">3</td>
                                        @if (@Model.TenNganh_TenToHop3 == null)
                                        {
                                            <td style=" line-height: 35px;"> @Model.TenNganh_TenToHop3</td>
                                        }
                                        else
                                        {
                                            <td style=" line-height: 35px;">@Model.TenNganh_TenToHop3.Split('#')[0]</td>
                                        }
                                        @if (@Model.MaNganh_ToHop3 == null)
                                        {
                                            <td style=" line-height: 35px;"> @Model.MaNganh_ToHop3</td>
                                        }
                                        else
                                        {
                                            <td style=" line-height: 35px;">@Model.MaNganh_ToHop3.Split('#')[0]</td>
                                        }
                                        <td style=" line-height: 35px;" class="txt-oflo">@Model.CTDT3</td>
                                    </tr>

                                    <!--     -->
                                    <!--     -->
                                    <!--     -->
                                </tbody>

                            </table>
                            <a href="@Url.Action("Index","ManageTHPT")"><button style="border:none; background-color: #fff; outline: none;"><i style="font-size: 30px;" class="fas fa-reply"></i></button></a>
                            <a role="button" class="btn d-grid btn-danger text-white" style="text-align:center" href="@Url.Action("NhanHoSo","ManageTHPT",new {id = Model.ID })">Nhận hồ sơ</a>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div><button onclick="topFunction()" id="myBtn" title="Go to top"><i class="gg-arrow-up-o"></i></button></div>
    <script src="plugins/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="js/app-style-switcher.js"></script>
    <script src="plugins/bower_components/jquery-sparkline/jquery.sparkline.min.js"></script>
    <!--Wave Effects -->
    <script src="js/waves.js"></script>
    <!--Menu sidebar -->
    <script src="js/sidebarmenu.js"></script>
    <!--Custom JavaScript -->
    <script src="js/custom.js"></script>
    <!--This page JavaScript -->
    <!--chartis chart-->
    <script src="plugins/bower_components/chartist/dist/chartist.min.js"></script>
    <script src="plugins/bower_components/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>
    <script src="js/pages/dashboards/dashboard1.js"></script>
</body>

</html>-